spring:
  # Data Source
  datasource:
    # 在MySQL的8.x以后的驱动包名中多了一个cj
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/site?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  # JPA 相关的配置
  jpa:
    # 数据库的版本
    database-platform: MySQL57
    hibernate:
      # 生成DDL语句，创建表
      ddl-auto: update
  mvc.view:
    prefix: /WEB-INF/views/
    suffix: .jsp
  servlet.multipart:
    # 可以不写单位，默认是MB，建议写单位
    # KB、MB、GB、TB
    maxFileSize: 10MB
  # 配置Redis数据库
  redis:
    database: 3
    host: 10.0.0.200
    port: 6379